"""create cartridge management tables

Revision ID: 0cb8e11fac9b
Revises: c1342def32fe
Create Date: 2026-08-19 17:37:41.307100

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cb8e11fac9b'
down_revision: Union[str, None] = 'c1342def32fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engineers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engineers_employee_id'), 'engineers', ['employee_id'], unique=True)
    op.create_table('locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_name'), 'locations', ['name'], unique=True)
    op.create_table('printers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model', sa.String(length=150), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_index(op.f('ix_printers_location_id'), 'printers', ['location_id'], unique=False)
    op.create_index(op.f('ix_printers_model'), 'printers', ['model'], unique=False)
    op.create_table('cartridges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model', sa.String(length=150), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('printer_id', sa.Integer(), nullable=False),
    sa.Column('reorder_level', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['printer_id'], ['printers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cartridges_model'), 'cartridges', ['model'], unique=False)
    op.create_index(op.f('ix_cartridges_printer_id'), 'cartridges', ['printer_id'], unique=False)
    op.create_table('cartridge_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('printer_id', sa.Integer(), nullable=False),
    sa.Column('cartridge_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', 'ISSUED', name='cartridge_request_status'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cartridge_id'], ['cartridges.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['printer_id'], ['printers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cartridge_requests_approved_by'), 'cartridge_requests', ['approved_by'], unique=False)
    op.create_index(op.f('ix_cartridge_requests_cartridge_id'), 'cartridge_requests', ['cartridge_id'], unique=False)
    op.create_index(op.f('ix_cartridge_requests_location_id'), 'cartridge_requests', ['location_id'], unique=False)
    op.create_index(op.f('ix_cartridge_requests_printer_id'), 'cartridge_requests', ['printer_id'], unique=False)
    op.create_index(op.f('ix_cartridge_requests_requester_id'), 'cartridge_requests', ['requester_id'], unique=False)
    op.create_index(op.f('ix_cartridge_requests_status'), 'cartridge_requests', ['status'], unique=False)
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cartridge_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='ck_inventory_quantity_non_negative'),
    sa.ForeignKeyConstraint(['cartridge_id'], ['cartridges.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_cartridge_id'), 'inventory', ['cartridge_id'], unique=True)
    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cartridge_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.Enum('RECEIPT', 'ISSUE', 'ADJUSTMENT', 'RETURN', name='stock_movement_type'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('performed_by', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cartridge_id'], ['cartridges.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_movements_cartridge_id'), 'stock_movements', ['cartridge_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_created_at'), 'stock_movements', ['created_at'], unique=False)
    op.create_index(op.f('ix_stock_movements_movement_type'), 'stock_movements', ['movement_type'], unique=False)
    op.create_index(op.f('ix_stock_movements_performed_by'), 'stock_movements', ['performed_by'], unique=False)
    op.create_table('cartridge_issues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('engineer_id', sa.Integer(), nullable=False),
    sa.Column('printer_id', sa.Integer(), nullable=False),
    sa.Column('cartridge_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('issue_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_cartridge_issue_quantity_positive'),
    sa.ForeignKeyConstraint(['cartridge_id'], ['cartridges.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['engineer_id'], ['engineers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['printer_id'], ['printers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['request_id'], ['cartridge_requests.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cartridge_issues_cartridge_id'), 'cartridge_issues', ['cartridge_id'], unique=False)
    op.create_index(op.f('ix_cartridge_issues_employee_id'), 'cartridge_issues', ['employee_id'], unique=False)
    op.create_index(op.f('ix_cartridge_issues_engineer_id'), 'cartridge_issues', ['engineer_id'], unique=False)
    op.create_index(op.f('ix_cartridge_issues_location_id'), 'cartridge_issues', ['location_id'], unique=False)
    op.create_index(op.f('ix_cartridge_issues_printer_id'), 'cartridge_issues', ['printer_id'], unique=False)
    op.create_index(op.f('ix_cartridge_issues_request_id'), 'cartridge_issues', ['request_id'], unique=True)
    op.drop_table('issue_cartridges')
    op.drop_constraint(op.f('refresh_tokens_jti_key'), 'refresh_tokens', type_='unique')
    op.add_column('users', sa.Column('employee_id', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('username', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_employee_id'), 'users', ['employee_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'name')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_employee_id'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'username')
    op.drop_column('users', 'employee_id')
    op.create_unique_constraint(op.f('refresh_tokens_jti_key'), 'refresh_tokens', ['jti'], postgresql_nulls_not_distinct=False)
    op.create_table('issue_cartridges',
    sa.Column('issue_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('engineer_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('printer_model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('cartridge_model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('issue_date', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=False),
    sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('issue_id', name=op.f('issue_cartridges_pkey'))
    )
    op.drop_index(op.f('ix_cartridge_issues_request_id'), table_name='cartridge_issues')
    op.drop_index(op.f('ix_cartridge_issues_printer_id'), table_name='cartridge_issues')
    op.drop_index(op.f('ix_cartridge_issues_location_id'), table_name='cartridge_issues')
    op.drop_index(op.f('ix_cartridge_issues_engineer_id'), table_name='cartridge_issues')
    op.drop_index(op.f('ix_cartridge_issues_employee_id'), table_name='cartridge_issues')
    op.drop_index(op.f('ix_cartridge_issues_cartridge_id'), table_name='cartridge_issues')
    op.drop_table('cartridge_issues')
    op.drop_index(op.f('ix_stock_movements_performed_by'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_movement_type'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_created_at'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_cartridge_id'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_inventory_cartridge_id'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_cartridge_requests_status'), table_name='cartridge_requests')
    op.drop_index(op.f('ix_cartridge_requests_requester_id'), table_name='cartridge_requests')
    op.drop_index(op.f('ix_cartridge_requests_printer_id'), table_name='cartridge_requests')
    op.drop_index(op.f('ix_cartridge_requests_location_id'), table_name='cartridge_requests')
    op.drop_index(op.f('ix_cartridge_requests_cartridge_id'), table_name='cartridge_requests')
    op.drop_index(op.f('ix_cartridge_requests_approved_by'), table_name='cartridge_requests')
    op.drop_table('cartridge_requests')
    op.drop_index(op.f('ix_cartridges_printer_id'), table_name='cartridges')
    op.drop_index(op.f('ix_cartridges_model'), table_name='cartridges')
    op.drop_table('cartridges')
    op.drop_index(op.f('ix_printers_model'), table_name='printers')
    op.drop_index(op.f('ix_printers_location_id'), table_name='printers')
    op.drop_table('printers')
    op.drop_index(op.f('ix_locations_name'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_engineers_employee_id'), table_name='engineers')
    op.drop_table('engineers')
    # ### end Alembic commands ###