"""check for drift

Revision ID: 322ca6d635c2
Revises: a1b2c3d4e5f6
Create Date: 2026-08-25 12:10:31.560823

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '322ca6d635c2'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cartridge_requests_approved_by'), table_name='cartridge_requests')
    op.drop_index(op.f('ix_cartridge_requests_cartridge_id'), table_name='cartridge_requests')
    op.drop_index(op.f('ix_cartridge_requests_engineer_id'), table_name='cartridge_requests')
    op.drop_index(op.f('ix_cartridge_requests_location_id'), table_name='cartridge_requests')
    op.drop_index(op.f('ix_cartridge_requests_printer_id'), table_name='cartridge_requests')
    op.drop_index(op.f('ix_cartridge_requests_requester_id'), table_name='cartridge_requests')
    op.drop_index(op.f('ix_cartridge_requests_status'), table_name='cartridge_requests')
    op.drop_constraint(op.f('cartridge_requests_printer_id_fkey'), 'cartridge_requests', type_='foreignkey')
    op.drop_constraint(op.f('cartridge_requests_location_id_fkey'), 'cartridge_requests', type_='foreignkey')
    op.drop_constraint(op.f('cartridge_requests_requester_id_fkey'), 'cartridge_requests', type_='foreignkey')
    op.drop_constraint(op.f('cartridge_requests_approved_by_fkey'), 'cartridge_requests', type_='foreignkey')
    op.drop_constraint(op.f('cartridge_requests_cartridge_id_fkey'), 'cartridge_requests', type_='foreignkey')
    op.drop_constraint(op.f('fk_cartridge_requests_engineer_id'), 'cartridge_requests', type_='foreignkey')
    op.create_foreign_key(None, 'cartridge_requests', 'printers', ['printer_id'], ['id'])
    op.create_foreign_key(None, 'cartridge_requests', 'users', ['requester_id'], ['id'])
    op.create_foreign_key(None, 'cartridge_requests', 'cartridges', ['cartridge_id'], ['id'])
    op.create_foreign_key(None, 'cartridge_requests', 'locations', ['location_id'], ['id'])
    op.create_foreign_key(None, 'cartridge_requests', 'engineers', ['engineer_id'], ['id'])
    op.drop_column('cartridge_requests', 'approved_at')
    op.drop_column('cartridge_requests', 'approved_by')
    op.drop_index(op.f('ix_engineers_employee_id'), table_name='engineers')
    op.drop_column('engineers', 'employee_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('engineers', sa.Column('employee_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_engineers_employee_id'), 'engineers', ['employee_id'], unique=True)
    op.add_column('cartridge_requests', sa.Column('approved_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('cartridge_requests', sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cartridge_requests', type_='foreignkey')
    op.drop_constraint(None, 'cartridge_requests', type_='foreignkey')
    op.drop_constraint(None, 'cartridge_requests', type_='foreignkey')
    op.drop_constraint(None, 'cartridge_requests', type_='foreignkey')
    op.drop_constraint(None, 'cartridge_requests', type_='foreignkey')
    op.create_foreign_key(op.f('fk_cartridge_requests_engineer_id'), 'cartridge_requests', 'engineers', ['engineer_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('cartridge_requests_cartridge_id_fkey'), 'cartridge_requests', 'cartridges', ['cartridge_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('cartridge_requests_approved_by_fkey'), 'cartridge_requests', 'users', ['approved_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('cartridge_requests_requester_id_fkey'), 'cartridge_requests', 'users', ['requester_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('cartridge_requests_location_id_fkey'), 'cartridge_requests', 'locations', ['location_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('cartridge_requests_printer_id_fkey'), 'cartridge_requests', 'printers', ['printer_id'], ['id'], ondelete='RESTRICT')
    op.create_index(op.f('ix_cartridge_requests_status'), 'cartridge_requests', ['status'], unique=False)
    op.create_index(op.f('ix_cartridge_requests_requester_id'), 'cartridge_requests', ['requester_id'], unique=False)
    op.create_index(op.f('ix_cartridge_requests_printer_id'), 'cartridge_requests', ['printer_id'], unique=False)
    op.create_index(op.f('ix_cartridge_requests_location_id'), 'cartridge_requests', ['location_id'], unique=False)
    op.create_index(op.f('ix_cartridge_requests_engineer_id'), 'cartridge_requests', ['engineer_id'], unique=False)
    op.create_index(op.f('ix_cartridge_requests_cartridge_id'), 'cartridge_requests', ['cartridge_id'], unique=False)
    op.create_index(op.f('ix_cartridge_requests_approved_by'), 'cartridge_requests', ['approved_by'], unique=False)
    # ### end Alembic commands ###